//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.WhatIEat.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shane.Church.WhatIEat.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other apps by Shane Church.
        /// </summary>
        public static string AboutOtherAppsLabel {
            get {
                return ResourceManager.GetString("AboutOtherAppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string AboutReviewLabel {
            get {
                return ResourceManager.GetString("AboutReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Shane Church 2015.
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a simple food journal for windows phone.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eat designed by Danny Chapman from The Noun Project.
        /// </summary>
        public static string AppIconDescription {
            get {
                return ResourceManager.GetString("AppIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application icon.
        /// </summary>
        public static string AppIconLabel {
            get {
                return ResourceManager.GetString("AppIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT I EAT.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string CalendarLabel {
            get {
                return ResourceManager.GetString("CalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectedLabel {
            get {
                return ResourceManager.GetString("ConnectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectLabel {
            get {
                return ResourceManager.GetString("ConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string CsvExportLabel {
            get {
                return ResourceManager.GetString("CsvExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered a problem. I am sorry for the inconvenience.
        ///
        ///I would appreciate your assistance by sending the prepared error report. This will help with resolving the problem faster..
        /// </summary>
        public static string Diagnostics_MessageBox_Content {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string Diagnostics_MessageBox_Title {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing on this date. Add something!.
        /// </summary>
        public static string EmptyEntryListLabel {
            get {
                return ResourceManager.GetString("EmptyEntryListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries found. Add something!.
        /// </summary>
        public static string EmptySummaryListLabel {
            get {
                return ResourceManager.GetString("EmptySummaryListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable synchronization.
        /// </summary>
        public static string EnableSyncLabel {
            get {
                return ResourceManager.GetString("EnableSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to OneDrive.
        /// </summary>
        public static string ExcelExportButtonLabel {
            get {
                return ResourceManager.GetString("ExcelExportButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to excel export.
        /// </summary>
        public static string ExcelExportLabel {
            get {
                return ResourceManager.GetString("ExcelExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will export all of your journal entries as a Excel-compatible CSV file to your OneDrive..
        /// </summary>
        public static string ExcelExportText {
            get {
                return ResourceManager.GetString("ExcelExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I improve this application so that you would be willing to rate it 5 stars in the marketplace?.
        /// </summary>
        public static string FeedbackContent {
            get {
                return ResourceManager.GetString("FeedbackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string GiveFeedbackButton {
            get {
                return ResourceManager.GetString("GiveFeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string MealTypeBreakfast {
            get {
                return ResourceManager.GetString("MealTypeBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string MealTypeDinner {
            get {
                return ResourceManager.GetString("MealTypeDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string MealTypeLunch {
            get {
                return ResourceManager.GetString("MealTypeLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        public static string MealTypeSnack {
            get {
                return ResourceManager.GetString("MealTypeSnack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MealTypeUndefined {
            get {
                return ResourceManager.GetString("MealTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new entry.
        /// </summary>
        public static string NewEntryLabel {
            get {
                return ResourceManager.GetString("NewEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string NoThanksButton {
            get {
                return ResourceManager.GetString("NoThanksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special thanks to Paulo Caldiera for the excellent Portugese translation!.
        /// </summary>
        public static string PortugeseTranslationCredit {
            get {
                return ResourceManager.GetString("PortugeseTranslationCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string PrivacyPolicyLabel {
            get {
                return ResourceManager.GetString("PrivacyPolicyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove ads.
        /// </summary>
        public static string RemoveAdsLabel {
            get {
                return ResourceManager.GetString("RemoveAdsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate me.
        /// </summary>
        public static string ReviewLabel {
            get {
                return ResourceManager.GetString("ReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show entry timestamp?.
        /// </summary>
        public static string ShowEntryTimeStampLabel {
            get {
                return ResourceManager.GetString("ShowEntryTimeStampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summary.
        /// </summary>
        public static string SummaryLabel {
            get {
                return ResourceManager.GetString("SummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronizing....
        /// </summary>
        public static string SynchronizingLabel {
            get {
                return ResourceManager.GetString("SynchronizingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string SyncLabel {
            get {
                return ResourceManager.GetString("SyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to sync..
        /// </summary>
        public static string SyncLoginError {
            get {
                return ResourceManager.GetString("SyncLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sync at this time. Please try again later..
        /// </summary>
        public static string SyncUnknownError {
            get {
                return ResourceManager.GetString("SyncUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to technical support/feedback email.
        /// </summary>
        public static string TechnicalSupportEmailLabel {
            get {
                return ResourceManager.GetString("TechnicalSupportEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I Eat Feedback.
        /// </summary>
        public static string TechnicalSupportEmailSubject {
            get {
                return ResourceManager.GetString("TechnicalSupportEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An upgrade is available! Do you want to install the upgrade now?.
        /// </summary>
        public static string UpgradeText {
            get {
                return ResourceManager.GetString("UpgradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Available!.
        /// </summary>
        public static string UpgradeTitle {
            get {
                return ResourceManager.GetString("UpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your data could not be exported to OneDrive at this time. Please try again later..
        /// </summary>
        public static string UploadFailedMessage {
            get {
                return ResourceManager.GetString("UploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Failed.
        /// </summary>
        public static string UploadFailedTitle {
            get {
                return ResourceManager.GetString("UploadFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading....
        /// </summary>
        public static string UploadingLabel {
            get {
                return ResourceManager.GetString("UploadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been successfully uploaded to OneDrive..
        /// </summary>
        public static string UploadSuccessMessage {
            get {
                return ResourceManager.GetString("UploadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successful!.
        /// </summary>
        public static string UploadSuccessTitle {
            get {
                return ResourceManager.GetString("UploadSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
